"use client";

import { useState } from "react";
import { hashFormulation, type CertificateData } from "@/lib/hash-certificate";
import { QRCodeSVG } from "qrcode.react";

export default function TimestampCertificateWidget() {
  const [text, setText] = useState("");
  const [cert, setCert] = useState<CertificateData | null>(null);
  const [loading, setLoading] = useState(false);
  const [showHow, setShowHow] = useState(false);

  const handleGenerate = async () => {
    if (!text.trim()) return;
    setLoading(true);
    try {
      const result = await hashFormulation(text.trim());
      setCert(result);
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    if (!cert) return;
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(`
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <title>IP-SAKTI Prior-Possession Certificate</title>
        <style>
          body { font-family: "Georgia", serif; padding: 40px; color: #1C2321; }
          h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
          .meta { font-size: 0.85rem; color: #555; margin-bottom: 2rem; }
          .hash { font-family: monospace; font-size: 0.75rem; word-break: break-all;
                  background: #f4f4f4; padding: 12px; border-left: 3px solid #24463A; }
          .disclaimer { margin-top: 2rem; font-size: 0.8rem; color: #888; border-top: 1px solid #ccc; padding-top: 1rem; }
        </style>
      </head>
      <body>
        <h1>IP-SAKTI Prior-Possession Timestamp Certificate</h1>
        <p class="meta">Generated by IP-SAKTI Sahayak · Not a legal document · For defensive prior-art purposes only</p>
        <p><strong>Timestamp:</strong> ${cert.timestamp}</p>
        <p><strong>ISO 8601:</strong> ${cert.isoDate}</p>
        <p><strong>Character count:</strong> ${cert.textLength} characters</p>
        <p><strong>SHA-256 Hash (client-side, plaintext never transmitted):</strong></p>
        <div class="hash">${cert.hash}</div>
        <p class="disclaimer">
          This certificate records only the SHA-256 hash of the submitted text and a local timestamp.
          The formulation text itself was never sent to any server. This certificate does not constitute
          a patent filing, a legal right, or a legally binding document. It provides a timestamped 
          record that may be used as supporting evidence of prior possession. Consult a qualified IP 
          attorney to understand its evidentiary value.
        </p>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  const qrData = cert
    ? JSON.stringify({ hash: cert.hash, ts: cert.isoDate, source: "IP-SAKTI" })
    : "";

  return (
    <div className="widget-card timestamp-certificate">
      <div className="widget-card__header">
        <span className="widget-badge">Differentiator</span>
        <h3 className="widget-card__title">Prior-Possession Timestamp Certificate</h3>
        <p className="widget-card__subtitle">
          Generate a SHA-256 hash of your formulation text — entirely in your browser. Plaintext never leaves your device.
        </p>
      </div>

      {/* Collapsible "How this works" */}
      <div className="cert-how-works">
        <button
          id="cert-how-works-toggle"
          className="cert-how-works__toggle"
          onClick={() => setShowHow((v) => !v)}
          aria-expanded={showHow}
        >
          How this works
          <span className="time-badge__chevron">{showHow ? "▲" : "▼"}</span>
        </button>
        {showHow && (
          <div className="cert-how-works__panel">
            <p>This widget uses the <strong>Web Crypto API</strong> built into your browser:</p>
            <pre className="cert-code-block">{`// The exact code running in your browser:
const encoder = new TextEncoder();
const data = encoder.encode(yourText);
const hashBuffer = await crypto.subtle.digest("SHA-256", data);
const hashHex = Array.from(new Uint8Array(hashBuffer))
  .map(b => b.toString(16).padStart(2, "0"))
  .join("");
// → 64-character hex string, computed locally.
// Your text is NEVER sent to any server.`}</pre>
            <p>
              The resulting hash is deterministic — the same text always produces the same hash.
              Combined with a timestamp, this creates a tamper-evident record of when you possessed
              this formulation. It is useful as <em>supporting evidence of prior possession</em>,
              but is not a patent filing.
            </p>
          </div>
        )}
      </div>

      <div className="cert-form">
        <label htmlFor="cert-formulation-text" className="cert-form__label">
          Your formulation text
        </label>
        <textarea
          id="cert-formulation-text"
          className="cert-form__textarea"
          placeholder="Describe your formulation in detail — ingredients, proportions, preparation method..."
          value={text}
          onChange={(e) => setText(e.target.value)}
          rows={6}
        />
        <p className="cert-form__note">
          The text you enter stays in your browser. It is hashed client-side and never transmitted.
        </p>
        <button
          id="generate-certificate"
          className="btn-primary"
          onClick={handleGenerate}
          disabled={!text.trim() || loading}
        >
          {loading ? "Generating..." : "Generate Certificate"}
        </button>
      </div>

      {cert && (
        <div className="cert-result">
          <div className="cert-result__row">
            <div className="cert-result__details">
              <div className="cert-result__field">
                <span className="cert-result__field-label">Timestamp</span>
                <span className="cert-result__field-value">{cert.timestamp}</span>
              </div>
              <div className="cert-result__field">
                <span className="cert-result__field-label">Characters hashed</span>
                <span className="cert-result__field-value">{cert.textLength}</span>
              </div>
              <div className="cert-result__field cert-result__field--hash">
                <span className="cert-result__field-label">SHA-256</span>
                <code className="cert-result__hash">{cert.hash}</code>
              </div>
            </div>
            <div className="cert-result__qr">
              <QRCodeSVG
                value={qrData}
                size={120}
                bgColor="#F7F5EF"
                fgColor="#24463A"
                aria-label="QR code encoding hash and timestamp"
              />
              <p className="cert-result__qr-note">QR encodes hash + timestamp</p>
            </div>
          </div>

          <button
            id="download-certificate"
            className="btn-secondary cert-result__download"
            onClick={handlePrint}
          >
            Download / Print Certificate
          </button>

          <div className="cited-answer-card__disclaimer" role="note">
            <span className="disclaimer-icon">ⓘ</span>
            <span className="disclaimer-text">
              This certificate is a record of prior possession only. It does not constitute a patent filing or a legal right. Consult a qualified IP attorney to understand its evidentiary value.
            </span>
          </div>
        </div>
      )}
    </div>
  );
}
